### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by MiXT4PE** [coderaiser/smalltalk#13]
I tried this...
      const smalltalk= require('smalltalk');
      smalltalk
            .prompt('Question', 'How old are you?', '10')
            .then((value) => {
                console.log(value);
            })
            .catch(() => {
                console.log('cancel');
            });

 ...on those versions..
      "npm": "^6.0.1",
      "smalltalk": "^3.0.0"

...and end up with this:

App threw an error during load
C:\Users\MIXT4PE\Dropbox\10_Programming\01_WebDev\MIQ-Cockpit\node_modules\smalltalk\css\smalltalk.css:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { .smalltalk {
                                                                                                                                                           ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\MIXT4PE\Dropbox\10_Programming\01_WebDev\MIQ-Cockpit\node_modules\smalltalk\legacy\smalltalk.js:3:1)

**Comment by coderaiser** [comment]
What do you use to build `bundle`? If you are using `webpack` you shuld add `rules` to your [webpack.config.js](https://github.com/coderaiser/smalltalk/blob/v3.0.0/webpack.config.js#L11-L21) file:

```
{
    test: /\.css$/,
    loader: 'style-loader!css-loader!clean-css-loader',
}
```

**Comment by MiXT4PE** [comment]
I apologize for the inactivity I didn't get notified that you answered. I still have this problem with my electron.js application. Since I use electron natively I don't think I can change the webpack.config.js-file.

**Comment by coderaiser** [comment]
In this case you can add prebuilt script, just like in [example](https://github.com/coderaiser/smalltalk/blob/v3.2.2/example/index.html):

```html
<script src="/node_modules/dist/smalltalk.min.js"></script>
```

**Comment by MiXT4PE** [comment]
Where would I get that? Would I need to include the css as well?

**Comment by coderaiser** [comment]
You can take a look at `node_modules/smalltalk` directory, just fixed link.

**Comment by MiXT4PE** [comment]
OKay great. So I `moved smalltalk.min.js` into the same dir as `main.js` and added

`
const smalltalk = require('smalltalk.min.js');
`

but it throws:

```
App threw an error during load
Error: Cannot find module 'smalltalk.min.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (C:\Users\...redacted...\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\...redacted...\main.js:2:19)
    at Object.<anonymous> (C:\Users\...redacted...\main.js:52:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
```

**Comment by coderaiser** [comment]
If you require from current directory you should add `./` so it would be:

```js
const smalltalk = require('./smalltalk.min.js');
```

**Comment by MiXT4PE** [comment]
Thank you. Now it throws this tho:

```
App threw an error during load
ReferenceError: window is not defined
    at C:\Users\...redacted...\smalltalk.js:43:196
    at C:\Users\...redacted...\smalltalk.js:43:158
    at t.exports (C:\Users\...redacted...\smalltalk.js:43:3807)
    at Object.<anonymous> (C:\Users\...redacted...\smalltalk.js:7:328)
    at n (C:\Users\...redacted...\smalltalk.js:1:278)
    at Object.<anonymous> (C:\Users\...redacted...\smalltalk.js:61:100)
    at n (C:\Users\...redacted...\smalltalk.js:1:278)
    at C:\Users\...redacted...\smalltalk.js:1:1077
    at Object.<anonymous> (C:\Users\...redacted...\smalltalk.js:1:1086)
    at Object.<anonymous> (C:\Users\...redacted...\smalltalk.js:87:3)
```

**Comment by MiXT4PE** [comment]
This might be of help but it hasn't been updated for a long time:

https://github.com/m-prj/smalltalk

**Comment by coderaiser** [comment]
2 commits:
- add files to repo
- convert encoding to windows

Not very helpful 🙂

**Comment by coderaiser** [comment]
To use `window` you should create [BrowserWindow](https://electronjs.org/docs/api/browser-window), have you done this? Add this line to your html file:

```
<script src="/node_modules/smalltalk/dist/smalltalk.min.js"></script>
```

**Comment by coderaiser** [comment]
The thing is `smalltalk` creates a [modal window](https://en.wikipedia.org/wiki/Modal_window), a window inside browser, it can't be shown without a browser window.

**Comment by MiXT4PE** [comment]
Okay so I guess it's not fully electron compatible as it only lives within a window. Thank you for your help!

**Comment by laurent22** [comment]
The lib used to work with Electron just fine (at least in 2.x), but support for it was broken at some point. That's a pity because there's [no built-in prompt in Electron](https://github.com/electron/electron/issues/472) so this library was quite convenient for it.
