### ISSUE TITLE
How to build for windows?

### ISSUE THREAD

**Issue by hrueger** [coderaiser/smalltalk#18]
Hi,
I'd like to contribute to this repository by adding a dialog with a select option box, but I can't build the dist files. If I run `npm run build`, it just opens the `madrun.js` file in my editor (VSCode). It is the same with the other commands. 
How can I get this to work?

Im working on Windows 10 with node v11.11.0

**Comment by coderaiser** [comment]
Just added ability to build on windows. Is it works for you?

**Comment by hrueger** [comment]
Unfortunately, not.
If I run `npm run build`, I get:
```
path\to\project\smalltalk\node_modules\madrun\lib\madrun.js:113
        throw Error(`one of scripts not found: ${name}`);
        ^

Error: one of scripts not found: clean
    at path\to\project\smalltalk\node_modules\madrun\lib\madrun.js:113:15
    at Array.map (<anonymous>)
    at run (path\to\project\smalltalk\node_modules\madrun\lib\madrun.js:64:10)
    at series (path\to\project\smalltalk\node_modules\madrun\lib\madrun.js:38:22)
    at module.exports.run (path\to\project\smalltalk\node_modules\madrun\lib\madrun.js:29:12)
    at build (path\to\project\smalltalk\.madrun.js:15:20)
    at path\to\project\smalltalk\node_modules\madrun\lib\madrun.js:105:29
    at Array.map (<anonymous>)
    at run (path\to\project\smalltalk\node_modules\madrun\lib\madrun.js:64:10)
    at series (path\to\project\smalltalk\node_modules\madrun\lib\madrun.js:38:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smalltalk@4.0.2 build: `madrun build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smalltalk@4.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myusername\AppData\Roaming\npm-cache\_logs\2019-10-24T17_43_00_344Z-debug.log
```

When I run `npm run watch`, I get:
```

> smalltalk@4.0.2 watch path\to\project\smalltalk
> madrun watch

> nodemon --watch lib --watch test --exec
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): lib\**\* test\**\*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node lib/smalltalk.js`
path\to\project\smalltalk\css\smalltalk.css:1
.smalltalk {
^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (path\to\project\smalltalk\lib\smalltalk.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
[nodemon] app crashed - waiting for file changes before starting...
```

Would you like to have more debug information?

**Comment by coderaiser** [comment]
The thing is build step removed in [v4](https://github.com/coderaiser/smalltalk/releases/tag/v4.0.0). Why do you need it? You can just use `webpack` in the root of your project.

**Comment by hrueger** [comment]
I just wanted to make sure that my changes are compatible with the examples [here](https://github.com/coderaiser/smalltalk/tree/master/example)
But then I'll just test them as normal in my other projects. No problem!
