### ISSUE TITLE
Prompt type

### ISSUE THREAD

**Issue by ray73864** [coderaiser/smalltalk#23]
Currently the prompt only supports a type of 'password', is it possible to get this changed so that it can support any valid input type?

I currently have need for it to be 'type="number"' as the HTML page this is on is being viewed on a mobile device and I want the on-screen keyboard to only show up as a numeric keyboard.

**Comment by coderaiser** [comment]
That's amazing idea for a pull request :)

**Comment by ray73864** [comment]
I have no idea how to do that :(

I cloned the repository, ran 'npm install' on it, but when I do 'npm run build' it comes up with issues :(

```
root@web-debian:/var/www/assets/dist/source/smalltalk# npm run build

> smalltalk@4.0.2 build /var/www/assets/dist/source/smalltalk
> madrun build

/var/www/assets/dist/source/smalltalk/node_modules/find-up/index.js:8
module.exports = async (name, options = {}) => {
                       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/assets/dist/source/smalltalk/node_modules/madrun/bin/madrun.js:7:16)
    at Module._compile (module.js:571:32)

npm ERR! Linux 4.19.0-6-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! smalltalk@4.0.2 build: `madrun build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smalltalk@4.0.2 build script 'madrun build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smalltalk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     madrun build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smalltalk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smalltalk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/assets/dist/source/smalltalk/npm-debug.log
```

**Comment by coderaiser** [comment]
Please update to your [node version](https://nodejs.org/en/) to `v12`, `v7` is very old and deprecated :).

**Comment by ray73864** [comment]
I feel stupid now :)

Doing things with node.js is not my norm, but upgrading Node to v12 made it all work.

Now I can figure out a decent way to do this change and work out how to do a PR (not something I normally do either).

Waaay out of my comfort zone right now :P

**Comment by coderaiser** [comment]
> Doing things with node.js is not my norm, but upgrading Node to v12 made it all work.

The thing is [async-await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) functions [made available](https://node.green/#ES2017-features-async-functions) in [LTS](https://github.com/nodejs/Release#nodejs-release-working-group) since `node 8`.
